//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ffmpeg_convert.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class ffmpeg : global::System.Configuration.ApplicationSettingsBase {
        
        private static ffmpeg defaultInstance = ((ffmpeg)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ffmpeg())));
        
        public static ffmpeg Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./external/")]
        public string bin_location {
            get {
                return ((string)(this["bin_location"]));
            }
            set {
                this["bin_location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("x86")]
        public string arch {
            get {
                return ((string)(this["arch"]));
            }
            set {
                this["arch"] = value;
            }
        }
    }
}
